services:
  bilive:
    #build:
    #    context: .
    #    dockerfile: Dockerfile # Dockerfile-GPU
    image: ghcr.io/timerring/bilive:latest # ghcr.io/timerring/bilive-gpu:latest
    restart: always
    container_name: bilive_docker
    ports:
      - "22333:2233"
    tty: true
    stdin_open: true
    volumes:
      - ./app:/app